#!/usr/bin/env bash
# Pulls census data of state boundaries and extracts it to <project_root>/data/clean/state_bounds
# Do not manually run, this is for the Rmd file

FILE="cb_2016_us_state_20m"
PUTDIR="../../data/clean/state_bounds"

# Download the zip file
wget http://www2.census.gov/geo/tiger/GENZ2016/shp/$FILE.zip

# Extract data, delete the zip
unzip ./$FILE.zip
rm $FILE.zip

# Create folder if it doesn't exist, or do nothing if it does
mkdir -p $PUTDIR

# Move the file to the new folder
mv ./$FILE* $PUTDIR
