---
title: "model"
author: "Fanny Chow, Mackenzie Gray, Noah Johnson, Shane Caldwell"
date: "December 11, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

lib <- function(package_name) {
  if (!require(package_name, character.only = TRUE)) {
    install.packages(package_name, repos = "http://cran.us.r-project.org")
    library(package_name, character.only = TRUE)
  }
}

lib('dplyr')
lib('ggplot2')
lib('leaps')
lib('ggfortify')
lib('GGally')
```

```{r}

# Load normalized sightings data
all_years <- read.csv(file ="../../data/clean/all_states_normalized.csv")

#shave of 2016 for test set
all_years_training <- filter(all_years, year < 2014)
all_years_test <- filter(all_years, year >= 2014)
all.years.lm <- lm(sightings_per_100k ~ region + year + normalized_afb_count + per_capita_gdp_current + alienmovies_per_year,data = all_years_training)

allpossreg <- regsubsets(sightings_per_100k ~ region + year + normalized_afb_count + per_capita_gdp_current + alienmovies_per_year + internet_avg, data = all_years_training, nbest=6)

aprout <- summary(allpossreg)

mallow <- with(aprout,round(cbind(which,cp),3))

ggplot(all_years_training, aes(x =seq(1, length(alienmovies_per_year)), y = alienmovies_per_year )) + geom_point(shape=20, colour = all_years_training$year) + labs( title = "Percentage of Alien Movies Per Year\n1974 - 2015", x = "Index", y = "Percentage of alien movies per year") + theme(plot.title = element_text(hjust = 0.5))

ggplot(all_years_training, aes(x =seq(1, length(alienmovies_per_year)), y = per_capita_gdp_current )) + geom_point(shape=20, colour = all_years_training$year) + labs( title = "GDP Per Capita Per Year\n1974 - 2015", x = "Index", y = "GDP Per Capita") + theme(plot.title = element_text(hjust = 0.5))

ggplot(all_years_training, aes(x = per_capita_gdp_current, y = sightings_per_100k)) + geom_point(shape=20, colour = all_years_training$year) + labs( title = "GDP Per Year Vs Sightings\n1974 - 2015", x = "GDP Per Capita", y = "UFO Sightings") + theme(plot.title = element_text(hjust = 0.5))

best.lm <- lm(sightings_per_100k ~ region + year + per_capita_gdp_current +  internet_avg, data = all_years_training)
summary(best.lm)

autoplot(best.lm)
yhat <- predict(best.lm, all_years_test)

error <- (all_years_test$sightings_per_100k - yhat)
plot(error)
```