---
title: "Process all the data"
output: html_notebook
---

Step 0: Read in libraries 

```{r, message=FALSE, warning=FALSE}
#rm(list=ls())
library(tidyverse)
#library(purrr)
library(data.table)
library(janitor)
library(plyr)

#library(lmtest)
#library(plyr)
#library(tidyverse)
#library(ggplot2)
#library(ggrepel)
#library(GGally)
library(lubridate)
#library(zoo)
```


Step 2: Read in files
```{r}
my.directory <- "~/Google Drive/stat/UFOTracker/data"
setwd(my.directory)

beer.path <- "raw/brew_count_by_state_1984_2017.csv"
movies.path <- "raw/alien_movies_per_year.csv"
gdp.path<- "raw/gdp_per_capita_per_year.csv"
internet.rurality.path <- "raw/internet_by_rurality.csv"
usafbase.path <- "raw/usaf_base_locs.csv"
statepops.path <- "raw/state_pops.csv"

beer.raw <- fread(file.path(my.directory, beer.path), header=TRUE, na.strings=c("*", ""))

sightings.raw <- fread(file.path(my.directory, sightings.path), header = TRUE, na.strings = c("", "Unknown", "--"))

movies.raw <- fread(file.path(my.directory, movies.path), header = TRUE)

gdp.raw <- fread(file.path(my.directory, gdp.path), header = TRUE)

internet.rurality.raw <- fread(file.path(my.directory, internet.rurality.path), header = TRUE)

usafbase.raw <- fread(file.path(my.directory, usafbase.path), header = TRUE)

statepops.raw <- fread(file.path(my.directory, statepops.path), header = TRUE)

```


Step 3: Data cleaning  

```{r}
# clean up file
beer.db <- beer.raw %>% 
  filter(!is.na(STATE)) %>%
  filter(STATE != "Total") %>% 
  filter(STATE != "Other") %>% 
  filter(STATE != "* No reportable data") %>% 
  filter(STATE != "«This list will be updated quarterly.") %>% 
  rename(state = STATE) %>% 
  mutate(state = as.factor(state)) %>% 
  gather_("year", "breweries", as.character(seq(1984, 2017))) %>% 
  mutate(breweries = as.numeric(breweries)) %>% 
  filter(year >= 1984) %>% 
  filter(year <= 2016) %>% 
  #filter(state == "FL") %>% 
  mutate(year = as.numeric(year))
  
```

```{r}
sightings.db <- sightings.raw %>% 
  #filter(state=='FL') %>% 
  mutate(state = toupper(state)) %>% 
  mutate(year = as.numeric(format(as.Date(date_time, format="%m/%d/%y"),"%Y"))) %>% 
  filter(year >= 1974) %>% 
  filter(year <= 2016) %>%
  count(year, state) %>% 
  rename(sightings_year = n) %>% 
 filter(state %in% state.abb)
  
```

```{r}
movies.db <- movies.raw %>% 
  filter(year >= 1974) %>% 
  filter(year <= 2016)
```


```{r}
gdp.db <- gdp.raw %>% 
  clean_names() %>% 
  rename(year = year_and_category) %>% 
  filter(year >= 1974) %>% 
  select(year, per_capita_gdp_current)
```

```{r}
internet.rurality.db <- internet.rurality.raw %>% 
  rename(year = Year)
```

```{r}
usafbase.db <- usafbase.raw %>% 
  #filter(State == "FL") %>% 
  rename(state = State)
```

```{r}
statepops.raw$Name <- mapvalues(statepops.raw$Name, state.name, state.abb)
state_pops <- statepops.raw %>%
    filter(Name %in% state.abb) %>%
    select(one_of(c("1970", "1980", "1990", "2000", "2010"))) %>%
    apply(1, mean)
```



Join files together
```{r}
all.states.df <- sightings.db %>% 
  left_join(beer.db, by=c("year" = "year", "state"= "state")) %>% 
  left_join(gdp.db, by = c("year" = "year")) %>% 
  left_join(movies.db, by = c("year" = "year")) %>% 
  #left_join(sightings.db, by=c("year" = "year", "state = state")) %>% 
  #left_join(beer.db, by=c("year" = "year", "state =  state")) %>% 
  left_join(internet.rurality.db, by=c("year" = "year")) #%>% 
  #mutate(state = ifelse(is.na(state), "FL", "FL"))
```




Step 4: Write out
```{r}
write_csv(all.states.df, "raw/all_states.csv")
```
