---
title: "Modelling Draft 1"
author: "Fan Chow"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(data.table)
library(dplyr)
library(noncensus)
library(car)
library(MASS)
library(leaps)
```

```{r}
my.directory <- "~/Documents/DS\ HW/UFOTracker"

setwd(file.path(my.directory, "analysis"))


all.states.normalized.path <- "data/raw/all_states_normalized.csv"

all.states.normalized.raw <- fread(file.path(my.directory, all.states.normalized.path))
```


Filter out a smaller range of years for the dataset  
```{r}
all.states.normalized.db <- all.states.normalized.raw %>%
  mutate(year = as.numeric(year)) %>% 
  filter(year >= 1984) %>% 
  filter(year <= 2014) %>% 
  mutate(state = as.factor(state)) %>% 
  mutate(region = as.factor(region))
```


Try modelling with the smaller range of years and correct factor data types for categorical variables  
```{r}
ufo.fit <- lm(sightings_per_100k ~ ., data = all.states.normalized.db)
# ufo.fit <- step(sightings_per_100k ~ region + year + breweries +
    # afbase_per_state + per_capita_gdp_current, data = all.states.normalized.db, direction = "both")

# lm(formula = sightings_per_100k ~ region + year + breweries +
    # afbase_per_state + per_capita_gdp_current, data = all_years)

summary(ufo.fit)
```



```{r}
data("states")
# table(states$region)
table(all.states.normalized.db$region)
```



```{r}
plot(ufo.fit)
```


# Partial Regression Plot  

## Partial Regression plots for all
```{r}
avPlots(ufo.fit)
```

## partial Regression plot for smaller model  
```{r}
small.fit <- lm(sightings_per_100k ~ year + afbase_per_state + per_capita_gdp_current + region,  data=all.states.normalized.db)
summary(small.fit)

avPlots(small.fit)
```



```{r}
# allpossreg <- regsubsets(sightings_per_100k ~ region + year + breweries + afbase_per_state + per_capita_gdp_current + alienmovies_per_year, data = all.states.normalized.db, nbest=6)

# allpossreg
```










